/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopproject;

// User imports Afaq
import admin.AdminAccount;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import user.Account;
import user.Cart;
import user.Shop;
import user.User;


// Admin Imports Taimoor
import admin.Admin;
import admin.adminInventory;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.io.FileWriter;
import utils.UtilFuncs;
/**
 *
 * @author Afaq Qazi Taimoor Pervaiz
 */
public class gui extends javax.swing.JFrame {
    
    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        userTabPanel = new javax.swing.JPanel();
        userTabSidePanel = new javax.swing.JPanel();
        userTabAccountBtn = new javax.swing.JButton();
        UserTabCartBtn = new javax.swing.JButton();
        userTabShopBtn = new javax.swing.JButton();
        userTabAccountPanel = new javax.swing.JPanel();
        userLogoutBtn = new javax.swing.JButton();
        userFormPanel = new javax.swing.JPanel();
        userFormLabel4 = new javax.swing.JLabel();
        userFormUsernameField = new javax.swing.JTextField();
        userFormPasswordField = new javax.swing.JPasswordField();
        userFormLabel5 = new javax.swing.JLabel();
        userFormLabel6 = new javax.swing.JLabel();
        userFormLoginBtn = new javax.swing.JButton();
        userFormRegisterBtn = new javax.swing.JButton();
        userFormEmptyError = new javax.swing.JLabel();
        userFormAlreadRegisteredError = new javax.swing.JLabel();
        userFormIncorrectError = new javax.swing.JLabel();
        userFormRegisteredMsg = new javax.swing.JLabel();
        userTabCartPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userCartTable = new javax.swing.JTable();
        userCartCheckoutBtn = new javax.swing.JButton();
        userCartClearCartBtn = new javax.swing.JButton();
        userCartHeading = new javax.swing.JLabel();
        userCartTotalLabel = new javax.swing.JLabel();
        userTabShopPanel = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        shopTableScrollPane = new javax.swing.JScrollPane();
        shopItemsTable = new javax.swing.JTable();
        shopBuyItemBtn = new javax.swing.JButton();
        shopBuyItemBox = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        shopItemBoxLabel2 = new javax.swing.JLabel();
        shopItemBoxQtyField = new javax.swing.JTextField();
        shopItemBoxAddToCartBtn = new javax.swing.JButton();
        shopItemBoxCancelBtn = new javax.swing.JButton();
        shopEnterItemLabell = new javax.swing.JLabel();
        shopSearchBar = new javax.swing.JTextField();
        adminTabPanel = new javax.swing.JPanel();
        adminTabSidePanel = new javax.swing.JPanel();
        AdminAccountBtn = new javax.swing.JButton();
        AdminAccountInventoryBtn = new javax.swing.JButton();
        AdminTabInventoryPanel = new javax.swing.JPanel();
        adminInventoryHeading = new javax.swing.JLabel();
        adminInventoryAddBtn = new javax.swing.JButton();
        adminInventoryDeleteBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminInventoryTable = new javax.swing.JTable();
        adminInventoryEnterItemLabell1 = new javax.swing.JLabel();
        adminInventorySearchbar = new javax.swing.JTextField();
        adminInventoryUpdateQtyBtn = new javax.swing.JButton();
        adminInventoryUpdatePriceBtn = new javax.swing.JButton();
        AdminTabAccountPanel = new javax.swing.JPanel();
        adminFormPanel = new javax.swing.JPanel();
        AdminAccountLabel = new javax.swing.JLabel();
        AdminAccountUsername = new javax.swing.JLabel();
        AdminAccountUsernameTextField = new javax.swing.JTextField();
        AdminAccountPassword = new javax.swing.JLabel();
        AdminAccountPasswordField = new javax.swing.JPasswordField();
        AdminAccountRegisterBtn = new javax.swing.JButton();
        AdminAccountLoginBtn = new javax.swing.JButton();
        AdminAccountLogoutBtn = new javax.swing.JButton();
        adminInventoryItemInfoBox = new javax.swing.JPanel();
        adminInventoryInfoBoxEnterNameLabel = new javax.swing.JLabel();
        adminInventoryInfoBoxEnterQtyLabel = new javax.swing.JLabel();
        adminInventoryInfoBoxEnterPriceLabel = new javax.swing.JLabel();
        adminInventoryInfoBoxName = new javax.swing.JTextField();
        adminInventoryInfoBoxQty = new javax.swing.JTextField();
        adminInventoryInfoBoxPrice = new javax.swing.JTextField();
        adminInventoryInfoBoxOkBtn = new javax.swing.JButton();
        adminInventoryInfoBoxCancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                MainTabbedPaneStateChanged(evt);
            }
        });

        userTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTabSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        userTabAccountBtn.setText("Account");
        userTabAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTabAccountBtnActionPerformed(evt);
            }
        });

        UserTabCartBtn.setText("Cart");
        UserTabCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTabCartBtnActionPerformed(evt);
            }
        });

        userTabShopBtn.setText("Shop");
        userTabShopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTabShopBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userTabSidePanelLayout = new javax.swing.GroupLayout(userTabSidePanel);
        userTabSidePanel.setLayout(userTabSidePanelLayout);
        userTabSidePanelLayout.setHorizontalGroup(
            userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserTabCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userTabAccountBtn)
                    .addComponent(userTabShopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        userTabSidePanelLayout.setVerticalGroup(
            userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabSidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(userTabAccountBtn)
                .addGap(26, 26, 26)
                .addComponent(UserTabCartBtn)
                .addGap(27, 27, 27)
                .addComponent(userTabShopBtn)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        userTabPanel.add(userTabSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        userTabAccountPanel.setBackground(new java.awt.Color(204, 204, 204));

        userLogoutBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userLogoutBtn.setText("Logout");
        userLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogoutBtnActionPerformed(evt);
            }
        });

        userFormPanel.setForeground(new java.awt.Color(255, 0, 0));

        userFormLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        userFormLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormLabel4.setText("Enter Username and Password to Login or Register");

        userFormLabel5.setText(" Username:");

        userFormLabel6.setText(" Password:");

        userFormLoginBtn.setText("Login");
        userFormLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFormLoginBtnActionPerformed(evt);
            }
        });

        userFormRegisterBtn.setText("Register");
        userFormRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userFormRegisterBtnActionPerformed(evt);
            }
        });

        userFormEmptyError.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userFormEmptyError.setForeground(new java.awt.Color(255, 51, 51));
        userFormEmptyError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormEmptyError.setText("Username or Password is empty");

        userFormAlreadRegisteredError.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userFormAlreadRegisteredError.setForeground(new java.awt.Color(255, 51, 51));
        userFormAlreadRegisteredError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormAlreadRegisteredError.setText("This username is already registered");

        userFormIncorrectError.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userFormIncorrectError.setForeground(new java.awt.Color(255, 51, 51));
        userFormIncorrectError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormIncorrectError.setText("Username or Password is incorrect");

        userFormRegisteredMsg.setBackground(new java.awt.Color(102, 102, 102));
        userFormRegisteredMsg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userFormRegisteredMsg.setForeground(new java.awt.Color(0, 153, 0));
        userFormRegisteredMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormRegisteredMsg.setText("User have been Registered");

        javax.swing.GroupLayout userFormPanelLayout = new javax.swing.GroupLayout(userFormPanel);
        userFormPanel.setLayout(userFormPanelLayout);
        userFormPanelLayout.setHorizontalGroup(
            userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userFormPanelLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userFormUsernameField, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addComponent(userFormPasswordField)
                                .addComponent(userFormLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userFormLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userFormPanelLayout.createSequentialGroup()
                                    .addComponent(userFormRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(userFormLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))
                            .addGroup(userFormPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userFormEmptyError, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userFormIncorrectError, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(userFormPanelLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(userFormRegisteredMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userFormPanelLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(userFormLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userFormPanelLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(userFormAlreadRegisteredError, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        userFormPanelLayout.setVerticalGroup(
            userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userFormLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userFormLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userFormUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userFormLabel6)
                .addGap(5, 5, 5)
                .addComponent(userFormPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFormRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userFormLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFormEmptyError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userFormIncorrectError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(userFormRegisteredMsg)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(userFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userFormPanelLayout.createSequentialGroup()
                    .addContainerGap(292, Short.MAX_VALUE)
                    .addComponent(userFormAlreadRegisteredError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)))
        );

        javax.swing.GroupLayout userTabAccountPanelLayout = new javax.swing.GroupLayout(userTabAccountPanel);
        userTabAccountPanel.setLayout(userTabAccountPanelLayout);
        userTabAccountPanelLayout.setHorizontalGroup(
            userTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabAccountPanelLayout.createSequentialGroup()
                .addGroup(userTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTabAccountPanelLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(userLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userTabAccountPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(userFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userTabAccountPanelLayout.setVerticalGroup(
            userTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabAccountPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(userFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(userLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userTabPanel.add(userTabAccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, 580));

        userTabCartPanel.setBackground(new java.awt.Color(204, 204, 204));

        userCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Total Item Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(userCartTable);

        userCartCheckoutBtn.setText("Check Out Cart");
        userCartCheckoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCartCheckoutBtnActionPerformed(evt);
            }
        });

        userCartClearCartBtn.setText("Clear Cart");
        userCartClearCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userCartClearCartBtnActionPerformed(evt);
            }
        });

        userCartHeading.setBackground(new java.awt.Color(0, 0, 0));
        userCartHeading.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userCartHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCartHeading.setText("USER CART");

        userCartTotalLabel.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        userCartTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userCartTotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout userTabCartPanelLayout = new javax.swing.GroupLayout(userTabCartPanel);
        userTabCartPanel.setLayout(userTabCartPanelLayout);
        userTabCartPanelLayout.setHorizontalGroup(
            userTabCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabCartPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(userTabCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCartHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(userTabCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTabCartPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(userCartTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userTabCartPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(userTabCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userCartCheckoutBtn)
                            .addComponent(userCartClearCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        userTabCartPanelLayout.setVerticalGroup(
            userTabCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabCartPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(userCartCheckoutBtn)
                .addGap(18, 18, 18)
                .addComponent(userCartClearCartBtn)
                .addGap(50, 50, 50)
                .addComponent(userCartTotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userTabCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userCartHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        userTabPanel.add(userTabCartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, 950, -1));

        userTabShopPanel.setBackground(new java.awt.Color(204, 204, 204));
        userTabShopPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTabShopPanelMouseClicked(evt);
            }
        });

        Heading.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Heading.setText("Select an item OR search for the item in the searchbar below");

        shopItemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shopTableScrollPane.setViewportView(shopItemsTable);

        shopBuyItemBtn.setText("Buy Item");
        shopBuyItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopBuyItemBtnActionPerformed(evt);
            }
        });

        shopBuyItemBox.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Please Fill out the Details Below:");

        shopItemBoxLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        shopItemBoxLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopItemBoxLabel2.setText("Enter the quantity of item you are purchasing:");

        shopItemBoxAddToCartBtn.setText("Add Item To Cart");
        shopItemBoxAddToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopItemBoxAddToCartBtnActionPerformed(evt);
            }
        });

        shopItemBoxCancelBtn.setText("Cancel");
        shopItemBoxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopItemBoxCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shopBuyItemBoxLayout = new javax.swing.GroupLayout(shopBuyItemBox);
        shopBuyItemBox.setLayout(shopBuyItemBoxLayout);
        shopBuyItemBoxLayout.setHorizontalGroup(
            shopBuyItemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                .addGroup(shopBuyItemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(shopItemBoxAddToCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(shopItemBoxQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(shopItemBoxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(shopItemBoxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        shopBuyItemBoxLayout.setVerticalGroup(
            shopBuyItemBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopBuyItemBoxLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopItemBoxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopItemBoxQtyField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(shopItemBoxAddToCartBtn)
                .addGap(18, 18, 18)
                .addComponent(shopItemBoxCancelBtn)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        shopEnterItemLabell.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        shopEnterItemLabell.setText("Enter Items to search:");

        shopSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopSearchBarActionPerformed(evt);
            }
        });
        shopSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                shopSearchBarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout userTabShopPanelLayout = new javax.swing.GroupLayout(userTabShopPanel);
        userTabShopPanel.setLayout(userTabShopPanelLayout);
        userTabShopPanelLayout.setHorizontalGroup(
            userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabShopPanelLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabShopPanelLayout.createSequentialGroup()
                        .addComponent(shopBuyItemBtn)
                        .addGap(431, 431, 431))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabShopPanelLayout.createSequentialGroup()
                        .addComponent(shopTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
            .addGroup(userTabShopPanelLayout.createSequentialGroup()
                .addGroup(userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userTabShopPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userTabShopPanelLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(shopEnterItemLabell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shopSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabShopPanelLayout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(shopBuyItemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
        userTabShopPanelLayout.setVerticalGroup(
            userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabShopPanelLayout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shopEnterItemLabell, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(shopSearchBar))
                .addGap(18, 18, 18)
                .addComponent(shopTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shopBuyItemBtn)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(userTabShopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabShopPanelLayout.createSequentialGroup()
                    .addContainerGap(130, Short.MAX_VALUE)
                    .addComponent(shopBuyItemBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );

        userTabPanel.add(userTabShopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, 950, -1));

        MainTabbedPane.addTab("User Tab", userTabPanel);

        adminTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminTabSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        AdminAccountBtn.setText("Account");
        AdminAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAccountBtnActionPerformed(evt);
            }
        });

        AdminAccountInventoryBtn.setText("Inventory");
        AdminAccountInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAccountInventoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTabSidePanelLayout = new javax.swing.GroupLayout(adminTabSidePanel);
        adminTabSidePanel.setLayout(adminTabSidePanelLayout);
        adminTabSidePanelLayout.setHorizontalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AdminAccountBtn)
                    .addComponent(AdminAccountInventoryBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminTabSidePanelLayout.setVerticalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabSidePanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(AdminAccountBtn)
                .addGap(43, 43, 43)
                .addComponent(AdminAccountInventoryBtn)
                .addContainerGap(448, Short.MAX_VALUE))
        );

        adminTabPanel.add(adminTabSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        adminInventoryHeading.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adminInventoryHeading.setText("Inventory: Select an item from the table to ADD, UPDATE or DELETE");

        adminInventoryAddBtn.setText("Add Item");
        adminInventoryAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryAddBtnActionPerformed(evt);
            }
        });

        adminInventoryDeleteBtn.setText("Delete Item");
        adminInventoryDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryDeleteBtnActionPerformed(evt);
            }
        });

        adminInventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(adminInventoryTable);
        if (adminInventoryTable.getColumnModel().getColumnCount() > 0) {
            adminInventoryTable.getColumnModel().getColumn(0).setResizable(false);
            adminInventoryTable.getColumnModel().getColumn(1).setResizable(false);
            adminInventoryTable.getColumnModel().getColumn(2).setResizable(false);
        }

        adminInventoryEnterItemLabell1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminInventoryEnterItemLabell1.setText("Enter Items to search:");

        adminInventorySearchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventorySearchbarActionPerformed(evt);
            }
        });
        adminInventorySearchbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                adminInventorySearchbarKeyReleased(evt);
            }
        });

        adminInventoryUpdateQtyBtn.setText("Update Item Quantity");
        adminInventoryUpdateQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryUpdateQtyBtnActionPerformed(evt);
            }
        });

        adminInventoryUpdatePriceBtn.setText("Update Item Price");
        adminInventoryUpdatePriceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryUpdatePriceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminTabInventoryPanelLayout = new javax.swing.GroupLayout(AdminTabInventoryPanel);
        AdminTabInventoryPanel.setLayout(AdminTabInventoryPanelLayout);
        AdminTabInventoryPanelLayout.setHorizontalGroup(
            AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                                .addComponent(adminInventoryEnterItemLabell1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adminInventorySearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(adminInventoryHeading))))
                .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(adminInventoryAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminInventoryUpdatePriceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryUpdateQtyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(adminInventoryDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(46, 46, 46))
        );
        AdminTabInventoryPanelLayout.setVerticalGroup(
            AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(adminInventoryAddBtn)
                        .addGap(43, 43, 43)
                        .addComponent(adminInventoryUpdateQtyBtn)
                        .addGap(39, 39, 39)
                        .addComponent(adminInventoryUpdatePriceBtn)
                        .addGap(41, 41, 41)
                        .addComponent(adminInventoryDeleteBtn))
                    .addGroup(AdminTabInventoryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adminInventoryHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AdminTabInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminInventoryEnterItemLabell1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventorySearchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        adminTabPanel.add(AdminTabInventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, 940, -1));

        AdminAccountLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminAccountLabel.setText("Enter Login Details here");

        AdminAccountUsername.setText("Username");

        AdminAccountPassword.setText("Password");

        AdminAccountRegisterBtn.setText("Register");
        AdminAccountRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAccountRegisterBtnActionPerformed(evt);
            }
        });

        AdminAccountLoginBtn.setText("Login");
        AdminAccountLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAccountLoginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminFormPanelLayout = new javax.swing.GroupLayout(adminFormPanel);
        adminFormPanel.setLayout(adminFormPanelLayout);
        adminFormPanelLayout.setHorizontalGroup(
            adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFormPanelLayout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(AdminAccountRegisterBtn)
                .addGap(71, 71, 71)
                .addComponent(AdminAccountLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adminFormPanelLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(adminFormPanelLayout.createSequentialGroup()
                            .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AdminAccountUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AdminAccountPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AdminAccountUsernameTextField)
                                .addComponent(AdminAccountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(adminFormPanelLayout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(AdminAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(101, Short.MAX_VALUE)))
        );
        adminFormPanelLayout.setVerticalGroup(
            adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminFormPanelLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminAccountLoginBtn)
                    .addComponent(AdminAccountRegisterBtn))
                .addGap(111, 111, 111))
            .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adminFormPanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(AdminAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AdminAccountUsername)
                        .addComponent(AdminAccountUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(49, 49, 49)
                    .addGroup(adminFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AdminAccountPassword)
                        .addComponent(AdminAccountPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(169, Short.MAX_VALUE)))
        );

        AdminAccountLogoutBtn.setText("Logout");
        AdminAccountLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminAccountLogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminTabAccountPanelLayout = new javax.swing.GroupLayout(AdminTabAccountPanel);
        AdminTabAccountPanel.setLayout(AdminTabAccountPanelLayout);
        AdminTabAccountPanelLayout.setHorizontalGroup(
            AdminTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTabAccountPanelLayout.createSequentialGroup()
                .addGroup(AdminTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminTabAccountPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(adminFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AdminTabAccountPanelLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(AdminAccountLogoutBtn)))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        AdminTabAccountPanelLayout.setVerticalGroup(
            AdminTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminTabAccountPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(adminFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(AdminAccountLogoutBtn)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        adminTabPanel.add(AdminTabAccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, 580));

        adminInventoryItemInfoBox.setPreferredSize(new java.awt.Dimension(950, 580));

        adminInventoryInfoBoxEnterNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminInventoryInfoBoxEnterNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInventoryInfoBoxEnterNameLabel.setText("Enter Item Name:");

        adminInventoryInfoBoxEnterQtyLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminInventoryInfoBoxEnterQtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInventoryInfoBoxEnterQtyLabel.setText("Enter Item Quantity");

        adminInventoryInfoBoxEnterPriceLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        adminInventoryInfoBoxEnterPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInventoryInfoBoxEnterPriceLabel.setText("Enter Item Price:");

        adminInventoryInfoBoxName.setMinimumSize(new java.awt.Dimension(200, 19));

        adminInventoryInfoBoxQty.setMinimumSize(new java.awt.Dimension(200, 19));

        adminInventoryInfoBoxPrice.setMinimumSize(new java.awt.Dimension(200, 19));

        adminInventoryInfoBoxOkBtn.setText("inset Items");
        adminInventoryInfoBoxOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryInfoBoxOkBtnActionPerformed(evt);
            }
        });

        adminInventoryInfoBoxCancelBtn.setText("Cancel");
        adminInventoryInfoBoxCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInventoryInfoBoxCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminInventoryItemInfoBoxLayout = new javax.swing.GroupLayout(adminInventoryItemInfoBox);
        adminInventoryItemInfoBox.setLayout(adminInventoryItemInfoBoxLayout);
        adminInventoryItemInfoBoxLayout.setHorizontalGroup(
            adminInventoryItemInfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminInventoryItemInfoBoxLayout.createSequentialGroup()
                .addGroup(adminInventoryItemInfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminInventoryItemInfoBoxLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addGroup(adminInventoryItemInfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminInventoryInfoBoxEnterNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryInfoBoxEnterQtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryInfoBoxEnterPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryInfoBoxName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryInfoBoxQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminInventoryInfoBoxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminInventoryItemInfoBoxLayout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(adminInventoryInfoBoxCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminInventoryInfoBoxOkBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        adminInventoryItemInfoBoxLayout.setVerticalGroup(
            adminInventoryItemInfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminInventoryItemInfoBoxLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(adminInventoryInfoBoxEnterNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminInventoryInfoBoxName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(adminInventoryInfoBoxEnterQtyLabel)
                .addGap(18, 18, 18)
                .addComponent(adminInventoryInfoBoxQty, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(adminInventoryInfoBoxEnterPriceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminInventoryInfoBoxPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(adminInventoryItemInfoBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminInventoryInfoBoxOkBtn)
                    .addComponent(adminInventoryInfoBoxCancelBtn))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        adminTabPanel.add(adminInventoryItemInfoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, 580));

        MainTabbedPane.addTab("Admin Tab", adminTabPanel);

        getContentPane().add(MainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // USER ACTION FUNCTON DO NOT INCLUDE ADMIN FUNCTION WITH THESE
    
    private void userTabAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTabAccountBtnActionPerformed
        // TODO add your handling code here:
        Account.show(this.userFormPanel , this.userLogoutBtn);
        Account.clearErrors(this.userFormEmptyError, this.userFormAlreadRegisteredError , this.userFormIncorrectError , this.userFormRegisteredMsg);
        this.userTabAccountPanel.setVisible(true);
        this.userTabCartPanel.setVisible(false);
        this.userTabShopPanel.setVisible(false);
    }//GEN-LAST:event_userTabAccountBtnActionPerformed

    private void UserTabCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTabCartBtnActionPerformed
        // TODO add your handling code here:
        if (User.isIsLoggedIn()) {
            this.userTabAccountPanel.setVisible(false);
            this.userTabCartPanel.setVisible(true);
            this.userTabShopPanel.setVisible(false);    
            this.userCartHeading.setText(User.getUsername().toUpperCase() + " CART:");
            // load cart items
            DefaultTableModel model =  (DefaultTableModel)this.userCartTable.getModel();
            Cart.loadItems(model);
            this.userCartTotalLabel.setText("Total Price: " + Cart.getTotalPrice(model));
        } else {
           JOptionPane.showMessageDialog(null, "User must be logged in in order to view Cart");
        }

    }//GEN-LAST:event_UserTabCartBtnActionPerformed

    private void userFormRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFormRegisterBtnActionPerformed
        // TODO add your handling code here:
        Account.clearErrors(this.userFormEmptyError,this.userFormAlreadRegisteredError, this.userFormIncorrectError , this.userFormRegisteredMsg);
        String username = this.userFormUsernameField.getText();
        String password = this.userFormPasswordField.getText();
        Account.registerUser(username , password , this.userFormEmptyError , this.userFormAlreadRegisteredError , this.userFormRegisteredMsg);
    }//GEN-LAST:event_userFormRegisterBtnActionPerformed

    private void userFormLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userFormLoginBtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model =  (DefaultTableModel)this.userCartTable.getModel();
        Cart.clearCart(model);
        
        Account.clearErrors(this.userFormEmptyError,this.userFormAlreadRegisteredError, this.userFormIncorrectError , this.userFormRegisteredMsg);        
        String username = this.userFormUsernameField.getText();
        String password = this.userFormPasswordField.getText();
        Account.loginUser(username , password , this.userFormEmptyError , this.userFormIncorrectError);
        // clear cart of previous user
        Account.show(this.userFormPanel , this.userLogoutBtn);
    }//GEN-LAST:event_userFormLoginBtnActionPerformed

    private void userLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogoutBtnActionPerformed
        // TODO add your handling code here:
        Account.logoutUser();
        // clear cart of previous user
        DefaultTableModel model =  (DefaultTableModel)this.userCartTable.getModel();
        Account.show(this.userFormPanel , this.userLogoutBtn);
        
    }//GEN-LAST:event_userLogoutBtnActionPerformed

    private void userTabShopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTabShopBtnActionPerformed
        if (User.isIsLoggedIn()) {
            // TODO add your handling code here:
            this.userTabAccountPanel.setVisible(false);
            this.userTabCartPanel.setVisible(false);
            this.userTabShopPanel.setVisible(true);

            // shopBuyItemBox should dissapear
            this.shopBuyItemBox.setVisible(false);
            this.shopTableScrollPane.setVisible(true);
            this.shopBuyItemBtn.setVisible(true);
            
            // searchbar should appear
            this.shopSearchBar.setVisible(true);
            this.shopEnterItemLabell.setVisible(true);

            // load items
            DefaultTableModel model =  (DefaultTableModel)this.shopItemsTable.getModel();
            Shop.loadItems(model);        
        } else {
            JOptionPane.showMessageDialog(null, "User must be logged in in order to view shop");
        }
    }//GEN-LAST:event_userTabShopBtnActionPerformed

    private void shopBuyItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopBuyItemBtnActionPerformed
        // TODO add your handling code here:
        
        if (this.shopItemsTable.getSelectedRow() != -1) {
            // item table should dissapear
            this.shopTableScrollPane.setVisible(false);
            this.shopBuyItemBox.setVisible(true);
            this.shopBuyItemBtn.setVisible(false);
            this.shopSearchBar.setVisible(false);
            this.shopEnterItemLabell.setVisible(false);
            
            DefaultTableModel model =  (DefaultTableModel)this.shopItemsTable.getModel();
            int selectedRow = this.shopItemsTable.getSelectedRow();
            String itemName = model.getValueAt(selectedRow, 0).toString();
            this.shopItemBoxLabel2.setText("Enter the amount of " + String.valueOf(itemName) + "s you want to buy:");
            
        } else {
            JOptionPane.showMessageDialog(null, "You must select an item to buy");
        }
    }//GEN-LAST:event_shopBuyItemBtnActionPerformed

    private void shopItemBoxAddToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopItemBoxAddToCartBtnActionPerformed
        // TODO add your handling code here:     
        DefaultTableModel model =  (DefaultTableModel)this.shopItemsTable.getModel();
        JTable table = this.shopItemsTable;
        String shopItemName =  model.getValueAt(table.getSelectedRow(), 0).toString();
        int shopItemQty = parseInt(model.getValueAt(table.getSelectedRow(), 1).toString()); 
        int userSelectedQty = 0;
        boolean shouldAddToCart;
        try {
            userSelectedQty = parseInt(this.shopItemBoxQtyField.getText());
            shouldAddToCart = true;
        } catch(NumberFormatException n ) {
            JOptionPane.showMessageDialog(null, "Please Enter a positive numeric value");
            shouldAddToCart = false;
        } 
        
        // check for negative number
        if (userSelectedQty < 0) {
            shouldAddToCart = false;
            JOptionPane.showMessageDialog(null, "Please Enter a positive numeric value");
        }
        
        if (shouldAddToCart) {
            if (userSelectedQty > shopItemQty) {
                JOptionPane.showMessageDialog(null, "Sorry only " + shopItemQty + " " + shopItemName + "s remaining");
            } else {
                model =  (DefaultTableModel)this.shopItemsTable.getModel();
                  table = this.shopItemsTable;
                Shop.addToCart(model , table , userSelectedQty , shopItemQty);
                this.shopBuyItemBox.setVisible(false);
                this.shopTableScrollPane.setVisible(true);
                this.shopBuyItemBtn.setVisible(true);
                this.shopSearchBar.setVisible(true);
                this.shopEnterItemLabell.setVisible(true);
                // load shop again since the qty in inventory is updated
                Shop.loadItems(model);
            }
        }
        
    }//GEN-LAST:event_shopItemBoxAddToCartBtnActionPerformed

    private void shopItemBoxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopItemBoxCancelBtnActionPerformed
        // TODO add your handling code here:
         this.shopTableScrollPane.setVisible(true);
         this.shopBuyItemBox.setVisible(false);
         this.shopBuyItemBtn.setVisible(true);
         this.shopItemBoxQtyField.setText("");
    }//GEN-LAST:event_shopItemBoxCancelBtnActionPerformed

    private void userCartClearCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCartClearCartBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)this.userCartTable.getModel(); 
        Cart.clearCart(model);
        this.userCartTotalLabel.setText("Total Price: " + Cart.getTotalPrice(model));
    }//GEN-LAST:event_userCartClearCartBtnActionPerformed

    private void userCartCheckoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userCartCheckoutBtnActionPerformed
        // TODO add your handling code here:
        if (this.userCartTable.getModel().getRowCount() > 0) {
            String label = this.userCartTotalLabel.getText();

            DefaultTableModel model =  (DefaultTableModel)this.userCartTable.getModel(); 
            if (Cart.checkout(label)) {
                // dont put back items into inventory but clear the cart model and cart file
                Cart.clearCartOnly(model);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There are no items in the cart");
        }
    }//GEN-LAST:event_userCartCheckoutBtnActionPerformed

    private void userTabShopPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTabShopPanelMouseClicked
        // TODO add your handling code here:
        // leavee empty
    }//GEN-LAST:event_userTabShopPanelMouseClicked

    private void shopSearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shopSearchBarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)this.shopItemsTable.getModel(); 
        Shop.loadItems(model);
        
        TableRowSorter sorter = new TableRowSorter(model);
        String searchedText = this.shopSearchBar.getText().toLowerCase();
        try {
            sorter.setRowFilter(RowFilter.regexFilter(searchedText , 0));
        } catch(PatternSyntaxException p) {
            model.setRowCount(0);
        }
        
        this.shopItemsTable.setModel(model);
        this.shopItemsTable.setRowSorter(sorter);
    }//GEN-LAST:event_shopSearchBarKeyReleased

    private void AdminAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAccountBtnActionPerformed
        // TODO add your handling code here:
        AdminAccount.show(adminFormPanel, AdminAccountLogoutBtn);
        this.AdminTabAccountPanel.setVisible(true);
        this.AdminTabInventoryPanel.setVisible(false);
        
    }//GEN-LAST:event_AdminAccountBtnActionPerformed

    private void AdminAccountRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAccountRegisterBtnActionPerformed
        // TODO add your handling code here:
        String username=this.AdminAccountUsernameTextField.getText();
        String password=this.AdminAccountPasswordField.getText();
        AdminAccount.RegisterAdmin(username, password);
        
    }//GEN-LAST:event_AdminAccountRegisterBtnActionPerformed

    private void AdminAccountLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAccountLoginBtnActionPerformed
        // TODO add your handling code here:
        String username=this.AdminAccountUsernameTextField.getText();
        String password=this.AdminAccountPasswordField.getText();
        AdminAccount.LoginButton(username,password);
        
         
         AdminAccount.show(this.adminFormPanel, AdminAccountLogoutBtn);
        
        
    }//GEN-LAST:event_AdminAccountLoginBtnActionPerformed

    private void AdminAccountLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAccountLogoutBtnActionPerformed
        // TODO add your handling code here:
        Admin.setIsLoggedIn(false);
                 System.out.println(Admin.isIsLoggedIn());

        AdminAccount.show(this.adminFormPanel, AdminAccountLogoutBtn);
        
        
    }//GEN-LAST:event_AdminAccountLogoutBtnActionPerformed

    private void AdminAccountInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminAccountInventoryBtnActionPerformed
        // TODO add your handling code here:
        if (Admin.isIsLoggedIn()) {
            this.AdminTabAccountPanel.setVisible(false);
            this.adminInventoryItemInfoBox.setVisible(false);   
            this.AdminTabInventoryPanel.setVisible(true);

            this.adminInventoryInfoBoxEnterNameLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterPriceLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterQtyLabel.setVisible(false);

            this.adminInventoryInfoBoxName.setVisible(false);
            this.adminInventoryInfoBoxQty.setVisible(false);
            this.adminInventoryInfoBoxPrice.setVisible(false);    
        } else {
            JOptionPane.showMessageDialog(null, "Admin must be logged in to view inventory");
        }

        
        // load items
        DefaultTableModel model =  (DefaultTableModel)this.adminInventoryTable.getModel(); 
        UtilFuncs.loadFromFileIntoATable("database/inventory.txt", model);
    }//GEN-LAST:event_AdminAccountInventoryBtnActionPerformed

    private void shopSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopSearchBarActionPerformed
        // TODO add your handling code here:
        // nothing to do here
    }//GEN-LAST:event_shopSearchBarActionPerformed

    private void adminInventorySearchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventorySearchbarActionPerformed
        // TODO add your handling code here:
        // nothing to do here
    }//GEN-LAST:event_adminInventorySearchbarActionPerformed

    private void adminInventorySearchbarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adminInventorySearchbarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model =  (DefaultTableModel)this.adminInventoryTable.getModel(); 
        UtilFuncs.loadFromFileIntoATable("database/inventory.txt", model);
        
        TableRowSorter sorter = new TableRowSorter(model);
        String searchedText = this.adminInventorySearchbar.getText().toLowerCase();
        try {
            sorter.setRowFilter(RowFilter.regexFilter(searchedText , 0));
        } catch(PatternSyntaxException p) {
            model.setRowCount(0);
        }
        
        this.adminInventoryTable.setModel(model);
        this.adminInventoryTable.setRowSorter(sorter);
    }//GEN-LAST:event_adminInventorySearchbarKeyReleased

    private void adminInventoryAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryAddBtnActionPerformed
        // TODO add your handling code here:
        this.AdminTabInventoryPanel.setVisible(false); 
        this.adminInventoryInfoBoxOkBtn.setText("Add Item");
        
        // remove all fields in info box
        this.adminInventoryInfoBoxEnterNameLabel.setVisible(false);
        this.adminInventoryInfoBoxEnterPriceLabel.setVisible(false);
        this.adminInventoryInfoBoxEnterQtyLabel.setVisible(false);
        this.adminInventoryInfoBoxName.setVisible(false);
        this.adminInventoryInfoBoxQty.setVisible(false);
        this.adminInventoryInfoBoxPrice.setVisible(false);
        
        // load relevant elemeents
        this.adminInventoryInfoBoxEnterNameLabel.setVisible(true);
        this.adminInventoryInfoBoxEnterPriceLabel.setVisible(true);
        this.adminInventoryInfoBoxEnterQtyLabel.setVisible(true);
        this.adminInventoryInfoBoxName.setVisible(true);
        this.adminInventoryInfoBoxPrice.setVisible(true);
        this.adminInventoryInfoBoxQty.setVisible(true);
        
        this.adminInventoryItemInfoBox.setVisible(true);
    }//GEN-LAST:event_adminInventoryAddBtnActionPerformed

    private void adminInventoryDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryDeleteBtnActionPerformed
        // TODO add your handling code here:
        this.adminInventoryInfoBoxOkBtn.setText("Delete Item");
        if (this.adminInventoryTable.getSelectedRow() != -1) {
            // delete item from inventory
            JTable table = this.adminInventoryTable;
            String selectedRowItemName = table.getValueAt(table.getSelectedRow(), 0).toString().trim().toLowerCase();
            adminInventory.deleteItem(selectedRowItemName);
            //reload invenitory;
            UtilFuncs.loadFromFileIntoATable("database/inventory.txt", (DefaultTableModel)table.getModel());
        } else {
            JOptionPane.showMessageDialog(null, "You must select an item to Delete it");
        }
    }//GEN-LAST:event_adminInventoryDeleteBtnActionPerformed

    private void adminInventoryInfoBoxOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryInfoBoxOkBtnActionPerformed
        // TODO add your handling code here:
        JTable table = this.adminInventoryTable;
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        String selectedRowItemName = "";
        int selectedRowItemQty = 0;
        double selectedRowItemPrice = 0;
        if (table.getSelectedRow() != -1) {
            selectedRowItemName = table.getValueAt(table.getSelectedRow(), 0).toString().trim().toLowerCase();
            selectedRowItemQty =  parseInt(table.getValueAt(table.getSelectedRow(), 1).toString());
            selectedRowItemPrice = Double.parseDouble(table.getValueAt(table.getSelectedRow(), 2).toString()); 
        }

        
        if (this.adminInventoryInfoBoxOkBtn.getText().equals("Add Item")) {
            try{
                String name = this.adminInventoryInfoBoxName.getText().trim().toLowerCase();
                String qty = this.adminInventoryInfoBoxQty.getText();
                String price = this.adminInventoryInfoBoxPrice.getText(); 
                if (name.equals("") || qty.equals("") || price.equals("") ) {
                    JOptionPane.showMessageDialog(null, "Please Fill all the required fields");
                } else {
                    int parsed_qty = parseInt(qty);
                    double parsed_price = Double.parseDouble(price);
                    if (parsed_qty <= 0 || parsed_price <=0) {
                        JOptionPane.showMessageDialog(null, "Please Enter a positive numerical value in quantity and price fields");
                    } else {
                        adminInventory.addItem(name , parsed_qty , parsed_price);
                        this.adminInventoryItemInfoBox.setVisible(false);
                        UtilFuncs.loadFromFileIntoATable("database/inventory.txt", model); 
                        this.adminInventoryInfoBoxName.setText("");
                        this.adminInventoryInfoBoxPrice.setText("");
                        this.adminInventoryInfoBoxQty.setText("");
                        this.AdminTabInventoryPanel.setVisible(true);
                    }
                }
            } catch(NumberFormatException  e) {
                JOptionPane.showMessageDialog(null, "Please Enter a positive numerical value in quantity and price fields");
            }
        } else if (this.adminInventoryInfoBoxOkBtn.getText().equals("Update Item Quantity")) {
            try{
                int qty = parseInt(this.adminInventoryInfoBoxQty.getText());
                if (qty <= 0) {
                    JOptionPane.showMessageDialog(null, "Please Enter a positive numerical value in quantity and price fields");
                } else {
                   adminInventory.updateQty(selectedRowItemName , qty);
                   this.adminInventoryItemInfoBox.setVisible(false);
                   UtilFuncs.loadFromFileIntoATable("database/inventory.txt", model); 
                   this.adminInventoryInfoBoxQty.setText("");
                   this.AdminTabInventoryPanel.setVisible(true);
                }
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Please enter a positive numerical value in quantity field");
            }
        } else {
            try{
                double price = Double.parseDouble(this.adminInventoryInfoBoxPrice.getText());
                if (price <= 0) {
                    JOptionPane.showMessageDialog(null,"Please enter a positive numerical value in quantity field");
                } else {
                     adminInventory.updatePrice(selectedRowItemName , price);
                    this.adminInventoryItemInfoBox.setVisible(false);
                    UtilFuncs.loadFromFileIntoATable("database/inventory.txt", model); 
                    this.adminInventoryInfoBoxPrice.setText("");
                    this.AdminTabInventoryPanel.setVisible(true);
                }
            } catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(null,"Please enter a numerical value in price field");
            }
        }
    }//GEN-LAST:event_adminInventoryInfoBoxOkBtnActionPerformed

    private void adminInventoryInfoBoxCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryInfoBoxCancelBtnActionPerformed
        // TODO add your handling code here:
        this.AdminTabInventoryPanel.setVisible(true);
        this.adminInventoryItemInfoBox.setVisible(false);
    }//GEN-LAST:event_adminInventoryInfoBoxCancelBtnActionPerformed

    private void adminInventoryUpdateQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryUpdateQtyBtnActionPerformed
        // TODO add your handling code here:
        if (this.adminInventoryTable.getSelectedRow() != -1) {
            this.AdminTabInventoryPanel.setVisible(false);
            this.adminInventoryInfoBoxOkBtn.setText("Update Item Quantity");

            // remove all fields in info box
            this.adminInventoryInfoBoxEnterNameLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterPriceLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterQtyLabel.setVisible(false);
            this.adminInventoryInfoBoxName.setVisible(false);
            this.adminInventoryInfoBoxQty.setVisible(false);
            this.adminInventoryInfoBoxPrice.setVisible(false);        

            // load relevant elemeents
            this.adminInventoryInfoBoxEnterQtyLabel.setVisible(true);
            this.adminInventoryInfoBoxQty.setVisible(true);        

            this.adminInventoryItemInfoBox.setVisible(true);        
        } else {
            JOptionPane.showMessageDialog(null, "You must select an item to update it");
        }

    }//GEN-LAST:event_adminInventoryUpdateQtyBtnActionPerformed

    private void adminInventoryUpdatePriceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminInventoryUpdatePriceBtnActionPerformed
        // TODO add your handling code here:
        if (this.adminInventoryTable.getSelectedRow() != -1) {
            this.AdminTabInventoryPanel.setVisible(false);
            this.adminInventoryInfoBoxOkBtn.setText("Update Item Price");

            // remove all fields in info box
            this.adminInventoryInfoBoxEnterNameLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterPriceLabel.setVisible(false);
            this.adminInventoryInfoBoxEnterQtyLabel.setVisible(false);
            this.adminInventoryInfoBoxName.setVisible(false);
            this.adminInventoryInfoBoxQty.setVisible(false);
            this.adminInventoryInfoBoxPrice.setVisible(false);     

            // load relevant elemeents
            this.adminInventoryInfoBoxPrice.setVisible(true);
            this.adminInventoryInfoBoxEnterPriceLabel.setVisible(true);       
            
            
            
            this.adminInventoryItemInfoBox.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "You must select an item to update it");
        }
    }//GEN-LAST:event_adminInventoryUpdatePriceBtnActionPerformed

    private void MainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_MainTabbedPaneStateChanged
        // TODO add your handling code here:
        DefaultTableModel inventoryModel = (DefaultTableModel) this.adminInventoryTable.getModel();
        DefaultTableModel cartModel = (DefaultTableModel) this.userCartTable.getModel();
        DefaultTableModel shopModel = (DefaultTableModel) this.shopItemsTable.getModel();
        
        UtilFuncs.loadFromFileIntoATable("database/inventory.txt", inventoryModel);
        UtilFuncs.loadFromFileIntoATable("database/cart.txt", cartModel);
        UtilFuncs.loadFromFileIntoATable("database/inventory.txt", shopModel);
    }//GEN-LAST:event_MainTabbedPaneStateChanged
    
    // USER ACTION FUNCTON END
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                gui a = new gui();
                a.setVisible(true);
                // this is so user does not see the account panel when he is not logged in
                a.userTabAccountPanel.setVisible(false);
                a.userTabCartPanel.setVisible(false);
                a.userTabShopPanel.setVisible(false);
                
                // Admin/taimoor code
                a.adminInventoryItemInfoBox.setVisible(false);
                a.AdminTabInventoryPanel.setVisible(false);
                a.adminFormPanel.setVisible(true);
                a.AdminAccountLogoutBtn.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminAccountBtn;
    private javax.swing.JButton AdminAccountInventoryBtn;
    private javax.swing.JLabel AdminAccountLabel;
    private javax.swing.JButton AdminAccountLoginBtn;
    private javax.swing.JButton AdminAccountLogoutBtn;
    private javax.swing.JLabel AdminAccountPassword;
    private javax.swing.JPasswordField AdminAccountPasswordField;
    private javax.swing.JButton AdminAccountRegisterBtn;
    private javax.swing.JLabel AdminAccountUsername;
    private javax.swing.JTextField AdminAccountUsernameTextField;
    private javax.swing.JPanel AdminTabAccountPanel;
    private javax.swing.JPanel AdminTabInventoryPanel;
    private javax.swing.JLabel Heading;
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton UserTabCartBtn;
    private javax.swing.JPanel adminFormPanel;
    private javax.swing.JButton adminInventoryAddBtn;
    private javax.swing.JButton adminInventoryDeleteBtn;
    private javax.swing.JLabel adminInventoryEnterItemLabell1;
    private javax.swing.JLabel adminInventoryHeading;
    private javax.swing.JButton adminInventoryInfoBoxCancelBtn;
    private javax.swing.JLabel adminInventoryInfoBoxEnterNameLabel;
    private javax.swing.JLabel adminInventoryInfoBoxEnterPriceLabel;
    private javax.swing.JLabel adminInventoryInfoBoxEnterQtyLabel;
    private javax.swing.JTextField adminInventoryInfoBoxName;
    private javax.swing.JButton adminInventoryInfoBoxOkBtn;
    private javax.swing.JTextField adminInventoryInfoBoxPrice;
    private javax.swing.JTextField adminInventoryInfoBoxQty;
    private javax.swing.JPanel adminInventoryItemInfoBox;
    private javax.swing.JTextField adminInventorySearchbar;
    private javax.swing.JTable adminInventoryTable;
    private javax.swing.JButton adminInventoryUpdatePriceBtn;
    private javax.swing.JButton adminInventoryUpdateQtyBtn;
    private javax.swing.JPanel adminTabPanel;
    private javax.swing.JPanel adminTabSidePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel shopBuyItemBox;
    private javax.swing.JButton shopBuyItemBtn;
    private javax.swing.JLabel shopEnterItemLabell;
    private javax.swing.JButton shopItemBoxAddToCartBtn;
    private javax.swing.JButton shopItemBoxCancelBtn;
    private javax.swing.JLabel shopItemBoxLabel2;
    private javax.swing.JTextField shopItemBoxQtyField;
    private javax.swing.JTable shopItemsTable;
    private javax.swing.JTextField shopSearchBar;
    private javax.swing.JScrollPane shopTableScrollPane;
    private javax.swing.JButton userCartCheckoutBtn;
    private javax.swing.JButton userCartClearCartBtn;
    private javax.swing.JLabel userCartHeading;
    private javax.swing.JTable userCartTable;
    private javax.swing.JLabel userCartTotalLabel;
    private javax.swing.JLabel userFormAlreadRegisteredError;
    private javax.swing.JLabel userFormEmptyError;
    private javax.swing.JLabel userFormIncorrectError;
    private javax.swing.JLabel userFormLabel4;
    private javax.swing.JLabel userFormLabel5;
    private javax.swing.JLabel userFormLabel6;
    private javax.swing.JButton userFormLoginBtn;
    private javax.swing.JPanel userFormPanel;
    private javax.swing.JPasswordField userFormPasswordField;
    private javax.swing.JButton userFormRegisterBtn;
    private javax.swing.JLabel userFormRegisteredMsg;
    private javax.swing.JTextField userFormUsernameField;
    private javax.swing.JButton userLogoutBtn;
    private javax.swing.JButton userTabAccountBtn;
    private javax.swing.JPanel userTabAccountPanel;
    private javax.swing.JPanel userTabCartPanel;
    private javax.swing.JPanel userTabPanel;
    private javax.swing.JButton userTabShopBtn;
    private javax.swing.JPanel userTabShopPanel;
    private javax.swing.JPanel userTabSidePanel;
    // End of variables declaration//GEN-END:variables
}
